/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AboutSectionRouteImport } from './routes/about.$section'
import { Route as InsightsSectionRouteImport } from './routes/insights.$section'
import { Route as ServicesServiceRouteImport } from './routes/services/$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSectionRoute = AboutSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AboutRoute,
} as any)
const InsightsSectionRoute = InsightsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => InsightsRoute,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/about/$section': typeof AboutSectionRoute
  '/insights/$section': typeof InsightsSectionRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/about/$section': typeof AboutSectionRoute
  '/insights/$section': typeof InsightsSectionRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/about/$section': typeof AboutSectionRoute
  '/insights/$section': typeof InsightsSectionRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/about/$section'
    | '/insights/$section'
    | '/services/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/about/$section'
    | '/insights/$section'
    | '/services/$service'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/about/$section'
    | '/insights/$section'
    | '/services/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ServicesServiceRoute: typeof ServicesServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$section': {
      id: '/about/$section'
      path: '/$section'
      fullPath: '/about/$section'
      preLoaderRoute: typeof AboutSectionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/insights/$section': {
      id: '/insights/$section'
      path: '/$section'
      fullPath: '/insights/$section'
      preLoaderRoute: typeof InsightsSectionRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutSectionRoute: typeof AboutSectionRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutSectionRoute: AboutSectionRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface InsightsRouteChildren {
  InsightsSectionRoute: typeof InsightsSectionRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSectionRoute: InsightsSectionRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ServicesServiceRoute: ServicesServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
